
server:
  port: 80
spring:
  config:
    activate:
      on-profile: dev

openapi:
  service:
    server: http://localhost:${server.port}
    server-name: dev
    title: API service Title
    api-docs: api-service
    version: 1.0.0

